### ISSUE TITLE
Minor issue when clan tag is invalid.

### ISSUE THREAD

**Issue by Jime86** [spAnser/discord-coc-war-announcer#1]
I made the mistake of typing in my clan tag in all lower case which resulted in the bot not working.  But on the call back to getCurrentWar if data is null, it returns no errors, so it left me scratching my head for a bit.

It might be worth testing initially if the clan tag is valid.

**Comment by spAnser** [comment]
If you type your clan  tag into https://developer.clashofclans.com/#/documentation under `/clans/{clanTag}/currentwar` does it return data for your clan?

**Comment by Jime86** [comment]
Yes it does, both upper case and in lower case form. But, for the bot, I had to manually upper case in config.js otherwise it just sat there and did nothing.

It's working now that it's upper case, and it looks great btw.

**Comment by spAnser** [comment]
Thanks I am making a hotfix to fix this issue. The reason is that the server always responds with the tag uppercased and Os replaced with 0s which break the linking.
