### ISSUE TITLE
Issues and suggestions for hitrate command

### ISSUE THREAD

**Issue by Pascal27** [spAnser/discord-coc-war-announcer#11]
First the suggestions for the **`hitrate`** command:

1. A header showing the clan names would be very helpful. At the moment you don't know instantly which is opponent and which is home clan.
2. What about TH 11 vs TH 11 3 stars?

**Bug reports**

- 10 vs 11 seems to be wrong. It shows 1/2 attacks for opponent although there was no attack from a TH 10 vs 11. But maybe I'm wrong and the second table is referring to the defenses and not opponent attacks?

![bildschirmfoto 2017-05-08 um 20 37 51](https://cloud.githubusercontent.com/assets/28492184/25819865/a5d0e4b2-342f-11e7-832f-2e1385dfaa86.png)

**Comment by spAnser** [comment]
Home team should always be on the left. I can add 11v11. The person who requests hitrate in the first place didn't ask for it so I stuck with what he asked for the begin with.

**Comment by spAnser** [comment]
Will be fixed in the next release. Is updated on the develop branch to include all TH levels 3 star.
