### ISSUE TITLE
Display issues with Android

### ISSUE THREAD

**Issue by taffy9** [spAnser/discord-coc-war-announcer#2]
Looks fine on web/desktop/iOS - but emojis not showing on Android: Discord issue.

https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/18524065-fix-emojis-inside-embeds-on-android

**Comment by spAnser** [comment]
This is a known issue with the discord app itself it cannot be fixed by anyone but the discord developers themselves.

I am going to leave this issue open until discord resolves the issue as to prevent others opening this same issue though.

**Comment by dineshKumar777** [comment]
Anybody having this issue, update the discord app. This is properly fixed with latest discord android update. 
Tested in my mobile.
