### ISSUE TITLE
Playerstats command showing max level for TH and completely

### ISSUE THREAD

**Issue by Pascal27** [spAnser/discord-coc-war-announcer#8]
I'm not sure if the star next to the level of the troop, spell and heroes should show that it is the maximum level but some suggestions about it:

- Use golden number if it is completely maxed

- Use a star next to the level if it is maxed for the townhall level of the user

Here an example:
![bildschirmfoto 2017-05-08 um 20 08 57](https://cloud.githubusercontent.com/assets/28492184/25818460/f23de908-342a-11e7-85ed-c9e372283902.png)

You can see that the star is missing for the last troop, spell or hero in a row.

**Comment by spAnser** [comment]
It shows a `*` for max level yes. I am not sure if you can custom text color on messages.

**Comment by Pascal27** [comment]
@spAnser All right, then it is missing for the last item in a row because healer, witch, haste spell, skeleton spell and warden are max.

**Comment by spAnser** [comment]
Will look into it thanks.

**Comment by IMGINI** [comment]
what's The command
